# .github/workflows/deploy.yml (in plant-disease-frontend repo)
name: Build and Deploy Angular App to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build Angular application for production
        run: npm run build -- --configuration production

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Your AWS region

      - name: Deploy static files to S3
        run: |
          aws s3 sync ./dist/plant-frontend/browser s3://your-s3-bucket-name --delete